### ISSUE TITLE
ES server error

### ISSUE THREAD

**Issue by kiteklan** [dlandon/zoneminder.machine.learning#180]
installed docker with variables, it failed on opencv on windows docker, manually installed opencv with build-compile-install , manually installed zmes ,all running on the zoneminder side but ES is giving below error on debug .

05/07/21 09:28:21 zmesdetect_m5[1472] FAT zm_detect.py:534 [Unrecoverable error:__init__() got an unexpected keyword argument 'logger' Traceback:Traceback (most recent call last): File "/var/lib/zmeventnotification/bin/zm_detect.py", line 531, in <module> main_handler() File "/var/lib/zmeventnotification/bin/zm_detect.py", line 378, in main_handler m = DetectSequence(options=ml_options, logger=g.logger) TypeError: __init__() got an unexpected keyword argument 'logger' ]

**Comment by kiteklan** [comment]
deleted all zmes folders manually and re-installed. no issues
